- src/commands/publish.js
When running `publish`, if the user uses the `--dappnode_team_preset` flag and the CLI is running in Travis (TRAVIS=true), use the custom provider "http://ipfs.dappnode.io"
> Add custom Travis provider

- src/methods/initializeDnp.js
- src/tasks/buildAndUpload.js
- src/utils/compose.js
- test/tasks/buildAndUpload.test.js
Prevents annoying errors where a manifest type release happens when you wanted to release a directory type release. Now the SDK will guess the type from the existence of `manifest.image`
Also on init the template is in directory type release, and present a better message as "next steps" for the user
```
lion$ dappnodesdk init -y -f
Your DAppNodePackage is ready: dappnodesdk.public.dappnode.eth
To start, you can:
- Develop your dockerized app in   ./build
- Add settings in the compose at   ./docker-compose.yml
- Add metadata in the manifest at  ./dappnode_package.json
Once ready, you can build, install, and test it by running
dappnodesdk build
```
> Directory debug

- src/params.ts
- src/tasks/buildAndUpload.ts
- src/types.ts
- src/utils/compose.ts
- src/utils/format.ts
- test/utils/compose.test.ts
Turns a compose like this one
```yaml
version: '3.4'
services:
validator:
image: sample-image
build:
args:
UPSTREAM_VERSION_PRYSM: v1.0.0-alpha.25
UPSTREAM_VERSION_LIGHTHOUSE: v0.2.9
```
to a manifest with
```json
{
"upstreamVersion": "Prysm: v1.0.0-alpha.25, Lighthouse: v0.2.9"
}
```
> Parse upstream version(s) from compose build args

- src/commands/githubActions/bumpUpstream/closeOldPrs.ts
- src/commands/githubActions/bumpUpstream/index.ts
- src/params.ts
- src/providers/github/Github.ts
The workflow of the added code is:
1. Get the branches of the repo where the bot has created a new PR
2. Iterate these branches and filter (only affect branches created by the bot and older than the new one) and obtain the PR associated with
3.  Comment on the old PR's and close them. Then Delete the branch associated
Extra:
The deleting process is not done by the octokit library because the library does not offer that functionality.
Only we have to test with the dappnode bot.
> Close old PRs on bump-upstream action

- src/tasks/buildAndUpload.ts
- src/tasks/createGithubRelease.ts
- src/utils/compose.ts
- test/utils/compose.test.ts
When installing the DAppNode ISO compose services have the `build` property which must be removed. Otherwise if the image is not properly loaded on the user side docker may trigger a build that will fail.
To do that we use a `sed` statement in the ISO scripts which is nasty, since it manipulates YAML in a fragile way causing issues:
- If `build` is not immediately followed by `image` it will delete all content in between.
The SDK now removes the `build` property when publishing, so the installer doesn't have to do that.
Closes https://github.com/dappnode/DAppNodeSDK/issues/172
Related https://github.com/dappnode/DAppNode_Installer/issues/161
> Remove build prop before uploading files

- src/commands/init.ts
fixed the license typo in manifest defaults, so it no longer is the incorrect GLP-3.0 but the proper GPL-3.0. once it's pushed, then i won't need to keep fixing new package manifests after they're published.
> Fix License typo in manifest defaults GPL > GPL

- src/commands/publish.ts
- src/releaseUploader/ipfsNode/ipfsProvider.ts
- test/commands/build.test.ts
Change DAppNode's hosted endpoint to https://api.ipfs.dappnode.io
> Migrate node to SSL

- src/commands/publish.ts
When working with the publish command I found some inconsistencies in the description. Hope to fix them with this.
Local build and test with `node dist/dappnodesdk.js publish --help` looked good.
> Fixed provider ports description

- src/commands/init.ts
- src/utils/releaseRecord.ts
This file is not meant to be committed, but a local offline record of the published versions you have done. To have a record of published versions we must use the releases page in Github.
> gitignore releases.json file

- src/files/compose/types.ts
- src/files/compose/validateDappnodeCompose.ts
- src/files/manifest/types.ts
- test/files/compose/validateDappnodeCompose.test.ts
Fix compose types:
- Add `ComposeVolumes` types
- Fix `ComposeNetworks` from `export type ComposeServiceNetworks = string[] | ComposeServiceNetworksObj[];` to `export type ComposeServiceNetworks = string[] | ComposeServiceNetworksObj;`
- Add `security_opt` key to compose service key whitelisted
> Fix compose types

- src/files/compose/params.ts
- test/files/compose/validateDappnodeCompose.test.ts
Set the minimum compose version as 3.4 until there is a full migration in dappnode packages to the version 3.5
> Set minimum compose version as 3.4

- src/tasks/buildAndUpload.ts
Related to https://github.com/dappnode/DAppNodeSDK/issues/250
Bypass the compose schema validation until got fixed
> Bypass compose JSON schema validation

- src/files/compose/params.ts
- src/files/compose/types.ts
Nethermind requires the ulimits compose feature to prevent from running out of memory
> Add compose key `ulimits`

- src/schemaValidation/schemas/setup-wizard.schema.json
- test/schemaValidation/validateSchema.test.ts
Allowed `service` to be an array of strings with at least 1 item
> Setup wizard: allow service to be an array for env variables

- src/files/manifest/types.ts
- src/schemaValidation/schemas/manifest.schema.json
- test/schemaValidation/validateSchema.test.ts
Allow to define which `globalEnvs` to be injected in the DAppNode package with an array of strings
> Add to `globalEnvs` the string array option

- src/schemaValidation/schemas/manifest.schema.json
- test/schemaValidation/validateSchema.test.ts
Currently there are two ways to inject global environment variables into a dappnode package: 
1. Defining the globalEnv to be injected in a specific service of the dappnode package
2. Injecting all
The second option is not a good approach and looks like an improbable option for a dappnode package to require all the global environment variables
> Deprecate `globalEnvs: {all: true}`

- src/commands/githubActions/endToEndTest/ensureDappnodeEnvironment.ts
Persist only staker prater config until more github self host runners are added
> Persist only staker prater config

- src/commands/githubActions/bumpUpstream/index.ts
`dappnode` provider was set as default, but for getting connection to this node, you need to be connected to a DAppNode, so now "remote" has been set as default value and `use_fallback` to true by default
> Fix bump upstream failure on trying to connect to "dappnode" provider

- src/commands/githubActions/endToEndTest/utils.ts
Do not execute proof of attestation for network mainnet
> Skip attestation proof if network is mainnet

- package.json
- src/tasks/generatePublishTx.ts
- src/utils/Apm.ts
- test/utils/Apm.test.ts
Since [toolkit](https://github.com/dappnode/toolkit) needs to be implemented in this SDK and uses ethers.js version 6.3.0, updating ethers from 5.X.X to 6.X.X on the SDK was necessary. These changes do not introduce any new functionalities or alter the code's logic; they simply update the ethers.js calls within the code.
At the time of writing this, the ethers.js v6 documentation is far from finished, so some updated calls lack proper documentation, but I have successfully initialized and published a DappNode package using this version of the SDK, and all tests have passed.
> update ethersjs to v6

- yarn.lock
Fix ens in yarn.lock, the generated in a mac (arm) was different than the generated in a amd architecture
> Fix ens in yarn.lock

- package.json
- yarn.lock
Hardcode ethers 6.3.0 version. There is an issue using `npx` and ethers 6.4.0 due to the `ens-normalize` subdependency not been possible to be downloaded with ssh
> hardcode ethers 6.3.0 version

- .github/ISSUE_TEMPLATE/bug_report.md
- src/utils/getLinks.ts
Continuing the work in this PR: https://github.com/dappnode/DAppNodeSDK/commit/028a0569263d5f1c861b17bcc0a1ea8ecf07a233
Update printed URL when building a package. Tested locally.
Before:
After:
> Update build print url

- src/commands/githubActions/bumpUpstream/index.ts
Bump action is failing on packages that have not been published, because the current package version cannot be fetched (`NO_REPO` exception). This error should not prevent the action from being run
> Avoid failure on bump to non-published pkg

- src/tasks/buildWithBuildx.ts
`libc-bin` caused segfaults on cross compiles with older qemu versions. This PR fixes that by using the new recommended binfmt instead of the deprecated one. Tested and works/fixes issues I had with cross compiles.
> fix: qemu version for cross builds

- src/commands/githubActions/bumpUpstream/index.ts
When the upstream version is identified as "release candidate" or "nightly" this si debugged in the console to avoid throwing an error.
> Debug console instead of throwing an error

- package.json
- src/files/compose/readCompose.ts
- yarn.lock
Bump `js-yaml` to 4.1.0 as this latest library version makes `yaml.load(...)` function safe by default, so that `safeLoad` is no longer needed
> Bump js-yaml to 4.1.0

- package.json
- yarn.lock
Bump schemas to 0.1.15 to allow the creation of packages with "Lido", "DVT" or "LSD" categories
> Bump schemas to 0.1.15

- package.json
- yarn.lock
Schemas 0.1.16 includes changes related to upstream repos, like defining `upstreamRepo` and `upstreamArg` fields and handling both simple strings, but also arrays of strings. The changes were made in this PR: https://github.com/dappnode/DNP_DAPPMANAGER/pull/1925
This overrides https://github.com/dappnode/DAppNodeSDK/pull/413
> Bump schemas to 0.1.16

- package.json
- src/commands/githubActions/bumpUpstream/index.ts
- src/commands/githubActions/bumpUpstream/settings/getInitialSettings.ts
- src/commands/githubActions/bumpUpstream/types.ts
- src/pinStrategy/index.ts
- src/pinStrategy/types.ts
- src/releaseUploader/pinata/PinataSDK.ts
- yarn.lock
Upstream sofware was previously defined like: `upstreamRepo`, `upstreamVersion` and `upstreamArg` in the manifest. They could receive a string or an array, so this has been migrated to a new format, defined in https://github.com/dappnode/DAppNodeSDK/issues/408
This PR will support both formats for the bump-upstream action
> Support new upstream format

- src/commands/githubActions/bumpUpstream/index.ts
- src/files/variants/getAllPackageVariants.ts
- src/params.ts
This PR enables bump action for template packages. Upstream version is updated in the common manifest and packages version is updated in each of the variant manifests
> Enable package template for bump action

- .github/workflows/release.yml
Create release action latest version is `v1`. It was mistakenly bumped to `v4`.
> Fix create-release action

- package.json
After failing to publish SDK to npm (due to a wrong version of `actions/create-release` fixed in https://github.com/dappnode/DAppNodeSDK/pull/423) the manifest version has been set to a wrong value
> Set latest SDK published version to 0.3.20

- src/commands/githubActions/bumpUpstream/github/isValidRelease.ts
Allowing non-semver releases for bump action. The previous approach would make the action fail for repos like https://github.com/dappnode/DAppNodePackage-monero, whose upstream repo is https://github.com/monero-project/monero, which includes release tags that do not follow semver. Instead, they look like: `v0.18.3.3`
Example: https://github.com/dappnode/DAppNodePackage-monero/actions/runs/9059682266/job/24887782261#step:3:17
> Allow non-semver releases

- src/providers/github/Github.ts
- src/tasks/buildAndUpload/buildVariantMap.ts
- test/commands/build.test.ts
Building packages that include the new upstream format in their manifest (https://github.com/dappnode/DAppNodePackage-holesky-obol/blob/374c1d0d6aebbbf38d96d53804e5de1b401d3f65/dappnode_package.json#L4) fail with this error:
https://github.com/dappnode/DAppNodePackage-DMS/actions/runs/9514324171/job/26226282057#step:3:25
This PR fixes it
> Fix build for new upstream format

- package.json
- src/commands/githubActions/build/index.ts
- src/commands/githubActions/bumpUpstream/github/closeOldPrs.ts
- src/commands/githubActions/bumpUpstream/index.ts
- src/providers/github/Github.ts
- src/tasks/createGithubRelease/subtasks/getCreateReleaseTask.ts
- src/tasks/publish/subtasks/getCreateGithubReleaseTask.ts
- yarn.lock
This PR aims to fix an issue that caused Github releases for packages not to be created after pushes to main branch. It includes bumping the `octokit` package to its latest version (`20.1.1`) and updating all the Github requests to match the REST API defined in https://docs.github.com/en/rest
> Bugfix: Create Github releases

- src/commands/githubActions/build/botComment.ts
- src/commands/githubActions/build/index.ts
- src/commands/githubActions/build/types.ts
- src/commands/githubActions/bumpUpstream/index.ts
Github Action build was omitting flags `variants` and `all-variants`, so it would not build multi-variant packages. This PR enables it
Furthermore, this PR aims to solve an existing issue, explained below:
Bot comment after github action build did not include the built hash, as shown here: https://github.com/dappnode/DNP_HTTPS/pull/94#issuecomment-2220296545
> Enable variants on github action build

- src/tasks/publish/subtasks/getUpdateFilesTask.ts
Updating the package version in both the compose and manifest files without updating the `images` property of the `variantsMap` would cause the following error to be thrown:
> Fix docker image not found error

- src/tasks/buildAndUpload/getBuildTasks.ts
- src/utils/getArchitecture.ts
- src/utils/parseArchitectures.ts
When building multi-arch packages in an ARM device (like latest Macs), the images built would be:
1. `arm64` (variant `v8`)
2. `arm64`
This would happen because native docker build was being used for AMD arch instead of `buildx`
> Fix AMD build on Mac

- src/commands/build/handler.ts
- src/commands/build/variants.ts
- src/commands/publish/handler.ts
- src/params.ts
- src/tasks/buildAndUpload/generatePackagesProps.ts
- src/tasks/buildAndUpload/getBuildTasks.ts
- src/tasks/buildAndUpload/getDeleteOldPinsTask.ts
- src/tasks/buildAndUpload/getFileCopyTask.ts
- src/tasks/buildAndUpload/getFileValidationTask.ts
- src/tasks/buildAndUpload/getReleaseDirCreationTask.ts
- src/tasks/buildAndUpload/getSaveUploadResultsTask.ts
- src/tasks/buildAndUpload/getUploadTasks.ts
- src/tasks/buildAndUpload/index.ts
- src/tasks/buildAndUpload/types.ts
- src/tasks/generatePublishTxs/index.ts
- src/tasks/publish/index.ts
- src/tasks/publish/subtasks/getBuildAndUploadTask.ts
- src/tasks/publish/subtasks/getFetchApmVersionsTask.ts
- src/tasks/publish/subtasks/getGenerateTxsTask.ts
- src/tasks/publish/subtasks/getUpdateFilesTask.ts
- src/tasks/publish/types.ts
- src/types.ts
- test/tasks/buildAndUpload/generatePackagesProps.test.ts
- test/utils/versions/updateVariantFiles.test.ts
This PR overrides https://github.com/dappnode/DAppNodeSDK/pull/440, as code base was out of date.
It aims to move from type:
```javascript
interface BuildVariantsMap {
[variant: string]: {
// Compose file
compose: Compose;
// Manifest-related
manifest: Manifest;
manifestFormat: ManifestFormat;
// File paths
releaseDir: string;
composePaths: string[];
// Package information
images: PackageImage[];
architectures: Architecture[];
}
}
```
to type:
```javascript
interface PackageToBuildProps {
variant: string | null;
// Compose file
compose: Compose;
// Manifest-related
manifest: Manifest;
manifestFormat: ManifestFormat;
// File paths
releaseDir: string;
composePaths: ComposePaths[];
manifestPaths: ManifestPaths[];
// Package information
images: PackageImage[];
architectures: Architecture[]; …
```
> Move from variant map to array (rebased)

- src/tasks/createGithubRelease/buildReleaseDetailsMap.ts
- src/tasks/createGithubRelease/getNextGitTag.ts
- src/tasks/createGithubRelease/types.ts
SDK publish action in mono-variant package repos would fail with this error:
```
[07:14:41] Release on github [started]
[07:14:41] Handle tags [started]
[07:14:41] Handle tags [failed]
[07:14:41] → Missing required release details for dappmanager.dnp.dappnode.eth
[07:14:41] Release on github [failed]
[07:14:41] → Missing required release details for dappmanager.dnp.dappnode.eth
✖ Missing required release details for dappmanager.dnp.dappnode.eth
Error: Missing required release details for dappmanager.dnp.dappnode.eth
at buildReleaseDetailsMap (file:///home/runner/.npm/_npx/7366de4368e80aba/node_modules/@dappnode/dappnodesdk/src/tasks/createGithubRelease/buildReleaseDetailsMap.ts:14:13)
at Task.task (file:///home/runner/.npm/_npx/7366de4368e80aba/node_modules/@dappnode/dappnodesdk/src/tasks/ …
```
> Fix git tag generation

- package.json
- src/tasks/buildAndUpload/buildWithCompose.ts
- yarn.lock
Replace legacy `docker-compose` binary in favour of new `compose` docker plugin for build task
> Use new compose plugin for build

- src/commands/init/fileOperations.ts
- src/commands/init/handler.ts
- src/commands/init/index.ts
Improve template repo init
Now the variant is set by a build arg, instead of an environment variable
> Improve template repo init

- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/test-ga-build.yml
- .github/workflows/test-ga-bump-upstream-template.yml
- .github/workflows/test-ga-bump-upstream.yml
- .github/workflows/test-ga-end-to-end.yml
- package.json
- src/utils/getFileHash.ts
- yarn.lock
When reading files at once and store it in memory using node there is a limitation of 2gb.  See https://nodejs.org/api/errors.html#err_fs_file_too_large
To avoid this error read file chunk by chunk
> Read file by chunks to avoid error of maximum size `ERR_FS_FILE_TOO_LARGE`

- package.json
- yarn.lock
Bump schemas to 0.1.22 to allow bind mount from tailscale
> Bump schemas to 0.1.22

- src/commands/publish/handler.ts
internal gh dappnode releases use the "dappnode_team_preset" flag, which uses infura's eth provider. This changes it to use dappnode's
> Use dappnode's remote ETH provider
