dappnode/DAppNodeSDK

src/tasks/buildAndUpload.js

Directory review

---

src/utils/commands/compressFile.js
src/utils/commands/execaProgress.js

Fixes https://github.com/dappnode/DAppNodeSDK/issues/51

Evalute execa return of null or 0

---

src/params.js
src/setup-wizard.schema.json
src/tasks/buildAndUpload.js

Include `setup-wizard.json` file and add preliminary JSON schema of `setup-wizard.json`

Add setup wizard 2 schema

---

package.json
src/dappnodesdk.ts
src/tasks/buildAndUpload.ts
src/types.ts
yarn.lock

Fixes https://github.com/dappnode/DAppNodeSDK/pull/77

Bump upstreamVersion if provided

---

src/commands/addAvatar.ts
src/commands/build.ts
src/commands/from_github.ts
src/commands/increase.ts
src/commands/init.ts
src/commands/next.ts
src/commands/publish.ts
src/dappnodesdk.ts
src/tasks/buildAndUpload.ts
src/types.ts

Allow to run the CLI directly with ts-node and provider more type safety

Declare commands with CommandModule

---

test/shellSafe.ts

Unix command rm -rf doesn't work on windows

Use rimraf instead of a unix command rm -r

---

src/schemas/manifest.schema.json

See https://github.com/dappnode/DNP_DAPPMANAGER/pull/683

Add manifest.exposable to schema

---

src/utils/Apm.ts
test/utils/Apm.test.ts

Add missing await here
https://github.com/dappnode/DAppNodeSDK/blob/b1fd61a1c0f1166c35ac6f20f6cf0e353e41416a/src/utils/Apm.ts#L72
Also simplify tests without conditional run if ()

Add missing await in APM consumer

---

src/commands/publish.ts
src/releaseUploader/ipfsNode/ipfsProvider.ts
test/commands/build.test.ts

HTTPS termination is giving us issues so until that is fixed reverting to HTTP.

Revert ipfs to http

---

.github/ISSUE_TEMPLATE/compose_request.md
.github/ISSUE_TEMPLATE/manifest_request.md
.github/ISSUE_TEMPLATE/setupWizard_request.md

Add issues templates for each release file:
- docker-compose
- setup-wizard
- manifest

Add issues templates for release files

---

src/files/compose/params.ts

Add pid to allowed keys
Fixes https://github.com/dappnode/DAppNodePackage-Erigon/runs/7078376322?check_suite_focus=true

Add pid to allowed keys

---

src/files/compose/types.ts
src/files/setupWizard/index.ts
src/files/setupWizard/readSetupWizardIfExists.ts
src/schemaValidation/validateSchema.ts
src/tasks/buildAndUpload.ts
test/schemaValidation/validateSchema.test.ts

- Fixes the setup-wizard validation file with the JSON schema
- Read setup-wizard file and validate only if it exists
- AJV validation less verbose

Fix setup-wizard validation

---

src/files/compose/types.ts

Add the number option to the compose env types

Add number to compose env types

---

src/files/compose/types.ts

Fix `compose` environment types according to docker compose file reference

Fix environment types

---

src/schemaValidation/schemas/manifest.schema.json
test/schemaValidation/validateSchema.test.ts

Do not allow to define additional properties in the dappnode manifest

Do not allow additional props in manifest

---

.github/workflows/test-ga-bump-upstream-master.yml
.github/workflows/test-ga-bump-upstream-template.yml
.github/workflows/test-ga-bump-upstream.yml
src/commands/githubActions/bumpUpstream/index.ts
src/params.ts
src/utils/readBuildSdkEnv.ts

Get the `UPSTREAM_REPO` and `UPSTREAM_VERSION` env values from the master env file `build_sdk.env` if exists before getting it from the normal manifest flow.

Add master env file checker for bum upstream gha

---

src/schemaValidation/schemas/manifest.schema.json
test/schemaValidation/validateSchema.test.ts

Allow additional properties in the manifest schema validation

Allow to define multiple additional properties in the manifest

---

src/files/manifest/types.ts

Set uid as optional for grafana dashboards

Set uid as optional

---

package.json
yarn.lock

Update ethers library to 5.7.2

Update ethers library

---

src/commands/init.ts
src/files/compose/getComposePackageImages.ts
src/files/compose/updateComposeImageTags.ts
src/params.ts
src/utils/getIsMonoService.ts
test/files/compose/updateComposeImageTags.test.ts
test/testUtils.ts

Take into account monoservice packages for compose image key

Take into account monoservice for compose image

---

src/files/compose/validateDappnodeCompose.ts

Throw error if monoservice pkg with service name on it

Throw error if monoservice pkg with service name on image

---

src/commands/init.ts
src/files/compose/getComposePackageImages.ts
src/files/compose/updateComposeImageTags.ts
src/files/compose/validateDappnodeCompose.ts
src/params.ts
src/utils/getIsMonoService.ts
test/files/compose/updateComposeImageTags.test.ts
test/testUtils.ts

Reverts dappnode/DAppNodeSDK#287

Revert "Take into account monoservice for compose image"

---

package.json
src/exports.ts
src/index.ts

Add exports to avoid exporting the whole entrypoint when using the sdk as a library

Add exports

---

package.json
src/commands/build.ts
src/commands/from_github.ts
src/commands/init.ts
src/commands/publish.ts
src/dappnodesdk.ts
src/exports.ts
src/files/manifest/types.ts
src/files/types.ts
src/providers/pinata/pinManager.ts
src/releaseUploader/ipfsNode/addDirFromUrls.ts
src/releaseUploader/ipfsNode/addFromFs.ts
src/releaseUploader/ipfsNode/ipfsVersion.ts
src/releaseUploader/pinata/addDirFromFs.ts
src/releaseUploader/pinata/index.ts
src/releaseUploader/swarmNode/addDirFromFs.ts
src/schemaValidation/index.ts
src/schemaValidation/validateSchema.ts
src/tasks/saveAndCompressImages.ts
src/types.ts
src/utils/githubGetReleases.ts
test/commands/gaBumpUpstream/format.test.ts
tsconfig.json

Modify exports and add modules

Modify exports

---

package.json

Add relative paths to exports

---

package.json
src/exports.ts

Add default exports endpoint

---

package.json

Add import to exports

---

src/commands/build.ts
src/commands/from_github.ts
src/commands/init.ts
src/commands/publish.ts
src/dappnodesdk.ts
src/providers/pinata/pinManager.ts
src/releaseUploader/ipfsNode/addDirFromUrls.ts
src/releaseUploader/ipfsNode/addFromFs.ts
src/releaseUploader/ipfsNode/ipfsVersion.ts
src/releaseUploader/pinata/addDirFromFs.ts
src/releaseUploader/pinata/index.ts
src/releaseUploader/swarmNode/addDirFromFs.ts
src/schemaValidation/validateSchema.ts
src/utils/githubGetReleases.ts
tsconfig.json

Set module resolution to `node`

Set module resolution to `node`

---

.github/workflows/test-ga-end-to-end.yml
src/commands/githubActions/endToEndTest/executeTests.ts

Add end to end workflow to be executed in a github self host runner

Add end to end workflow

---

src/commands/githubActions/endToEndTest/ensureDappnodeEnvironment.ts

Check that dappmanager docker alias resolve from the host machine, so healthChecksUrls can be check in the gha test-end-to-end

Set check resolver dappmanager alias from host

---

package.json

Edit script tag and publish to dont delete previous git tags

Edit script tag and publish

---

.github/workflows/release.yml
package.json

Use workflow dispatch to manually trigger sdk releases with input patch minor and major

Trigger release manually

---

src/commands/githubActions/endToEndTest/ensureDappnodeEnvironment.ts
src/commands/githubActions/endToEndTest/executeTests.ts
src/commands/githubActions/endToEndTest/index.ts
src/commands/githubActions/endToEndTest/params.ts
src/commands/githubActions/endToEndTest/types.ts
src/commands/githubActions/endToEndTest/utils.ts

Check network for staker packages tests and other fixes

Check network for staker packages tests

---

.github/workflows/test-ga-end-to-end.yml
src/commands/githubActions/endToEndTest/ensureDappnodeEnvironment.ts
src/commands/githubActions/endToEndTest/index.ts

Fix ensureDappnode env after exit

Fix ensureDappnode env after exit

---

src/commands/githubActions/endToEndTest/executeTests.ts
src/commands/githubActions/endToEndTest/testCheckers.ts

Execute all end to end tests even there are errors on previous tests. Finally throw an aggregated error

Execute every end to end test even previous throws error

---

src/commands/githubActions/endToEndTest/executeTests.ts
src/commands/githubActions/endToEndTest/index.ts

Print package metadata info in end to end test

Print package metadata info in end to end test

---

src/commands/githubActions/endToEndTest/ensureDappnodeEnvironment.ts
src/commands/githubActions/endToEndTest/executeTests.ts

Improve logger in end to end test

Improve logger in end to end test

---

src/commands/githubActions/endToEndTest/params.ts

Hardcode stake pkgs to keep in dappnode self host runner

Hardcode staker pkgs

---

src/commands/githubActions/endToEndTest/params.ts

Fix persist staker configuration per network

Fix persist staker config

---

src/commands/githubActions/endToEndTest/testCheckers.ts

Improve healthcheck checker in end to end test

Improve healthcheck checker

---

src/commands/githubActions/endToEndTest/executeTests.ts

Add network to end to tend test checkers

Add network to end to tend test checkers

---

src/commands/githubActions/endToEndTest/testCheckers.ts

Add identation to error message in end to end test

Add identation to error message in end to end test

---

src/commands/githubActions/endToEndTest/dappmanagerTestApi.ts

Remove volumes on package remove by default in end to end tests

Remove volumes on package remove by default

---

src/commands/githubActions/endToEndTest/params.ts

Do not use vars in staker params to avoid vars scope edits

Do not use vars in staker params

---

package.json

New SDK version has just been published here https://www.npmjs.com/package/@dappnode/dappnodesdk/v/0.2.98

Update SDK version in `package.json`

---

src/commands/publish.ts
src/releaseUploader/ipfsNode/ipfsProvider.ts
test/commands/build.test.ts

Links are now updated from `http://ipfs.dappnode.io` to `http://api.ipfs.dappnode.io`

Update IPFS links

---

src/commands/githubActions/endToEndTest/executeTests.ts
src/commands/githubActions/endToEndTest/index.ts
src/commands/githubActions/endToEndTest/params.ts
src/commands/githubActions/endToEndTest/types.ts
src/commands/githubActions/endToEndTest/utils.ts

Ensure the inmutability of the end to end test staker configuration and clean its code

Ensure inmutability and clean code from end to end test

---

package.json
yarn.lock

Bump dappnode types dependency to 0.1.12

Bump dappnode types dependency

---

src/commands/githubActions/endToEndTest/dappmanagerTestApi.ts
src/commands/githubActions/endToEndTest/executeTests.ts
src/commands/githubActions/endToEndTest/utils.ts

Removed CC volumes before installing from scratch (to simulate real installation from 0)

Remove CC volumes for e2e test

---

src/dappnodesdk.ts
src/index.ts

Add error handlers

---

src/dappnodesdk.ts

Remove unnecesary process on error handler

Remove unnecesary process on

---

src/commands/githubActions/endToEndTest/params.ts

Add ethical metrics pkg to allowed existing packages in tropis

Add ethical metrics pkg

---

package.json
src/commands/githubActions/endToEndTest/types.ts
src/commands/githubActions/endToEndTest/utils.ts
yarn.lock

Update dappnode dependencies:
- dappnode/types
- dappnode/toolkit

Update dappnode dependencies

---

README.md

Update sample GHA to current version, and one that works, added notes about secrets, and updated several lines for typos, formatting, capitalization, and reworded/rewrote some sentences to make them read easier and more clearly

Update wording, formatting, and update autocheck sample GHA

---

src/utils/getLinks.ts

Remove hash route for installer

Remove hash route

---

src/files/compose/index.ts
src/files/compose/params.ts

Remove unused docker params

---

package.json
yarn.lock

Hardcode schemas dependency to 0.1.8

Hardcode schemas dependency

---

package.json
yarn.lock

hardcode version dappnode types to 0.1.17

hardcode version dappnode types

---

package.json
yarn.lock

Bump dappnode types to 0.1.31

---

README.md
package.json
src/utils/versions/getNextVersionFromApm.ts
yarn.lock

Bump dappnode dependencies:
- schemas: 0.1.12
- types: 0.1.34
- toolkit: 0.1.21

Bump dappnode dependencies

---

package.json
src/commands/githubActions/bumpUpstream/format.ts
test/commands/gaBumpUpstream/format.test.ts
yarn.lock

Instead of checking with regex if proposed release has "-rc" or "nightly" on its version, checking it with semver lib

Checking if proposed release is desired with semver

---

package.json
src/commands/build.ts
src/commands/githubActions/build/index.ts
src/commands/githubActions/endToEndTest/index.ts
src/commands/publish.ts
src/files/compose/readCompose.ts
src/files/manifest/readManifest.ts
src/files/manifest/types.ts
src/params.ts
src/tasks/buildAndUpload.ts
src/tasks/buildWithBuildx.ts
src/tasks/buildWithCompose.ts
src/types.ts
test/commands/build.test.ts
yarn.lock

This PR allows the creation of different dappnode packages from a single repository using a kind of templating, defined in https://github.com/dappnode/DAppNodePackage-geth-generic

Add template mode to build command

---

src/commands/publish.ts
src/releaseUploader/ipfsNode/ipfsProvider.ts

Remove IPFS port API from dev node

Remove IPFS port API from dev node

---

.github/workflows/main.yml
.github/workflows/release.yml
.github/workflows/test-ga-build.yml
.github/workflows/test-ga-bump-upstream-template.yml
.github/workflows/test-ga-bump-upstream.yml
.github/workflows/test-ga-end-to-end.yml
README.md

Workflow action versions were quite out of date. This PR aims to bump them

Update workflow versions

---

package.json
src/tasks/buildAndUpload.ts
yarn.lock

Bump schemas to the newest version so that SDK supports merging compose files before testing compose format

Bump @dappnode/schemas to 0.1.20

---

src/tasks/publish/subtasks/getFetchApmVersionsTask.ts

After running `publish` command, the manifest version is increased according to the latest version fetched from the APM repository

Increase manifest version from APM

---

package.json
yarn.lock

Bump types to 0.1.40 and schemas to 0.1.23

Bump types to 0.1.40 and schemas to 0.1.23

---

src/files/index.ts
src/files/manifest/index.ts
src/files/notifications/index.ts
src/files/notifications/readNotificationsIfExists.ts
src/files/notifications/types.ts
src/files/setupWizard/index.ts
src/files/setupWizard/readSetupWizardIfExists.ts
src/files/setupWizard/types.ts
src/tasks/buildAndUpload/generatePackagesProps.ts
src/tasks/buildAndUpload/getFileCopyTask.ts
src/tasks/buildAndUpload/getFileValidationTask.ts
src/tasks/buildAndUpload/index.ts
src/types.ts
test/tasks/buildAndUpload/generatePackagesProps.test.ts

Implement notifications release file

Implement notifications release file
